name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  # amd64 job
  release_amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (for amd64)
        run: |
          sudo apt update
          sudo apt install cmake gcc-14 g++-14 p7zip-full mold ninja-build libpq-dev libtbb-dev libmimalloc-dev libboost1.83-dev libgmp-dev libmpfr-dev libre2-dev qt6-base-dev libsfml-dev libflatbuffers-dev libavcodec-dev libavdevice-dev libavformat-dev libavfilter-dev libavutil-dev libpostproc-dev libswscale-dev libsdl2-dev

      - name: Configure amd64 release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -Bbuild_release_amd64 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON

      - name: Build amd64 release
        run: |
          cmake --build build_release_amd64 --parallel

      - name: Create .tar.xz amd64 release artifact
        run: |
          tar -Jcvf release_amd64.tar.xz -C build_release_amd64 bin/

      - name: Create .7z amd64 release artifact
        run: |
          cd build_release_amd64 && 7z a ../release_amd64.7z bin/

      - name: Upload amd64 release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_amd64.tar.xz, release_amd64.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # amd64-avx2 job
  release_amd64_avx2:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (for amd64-avx2)
        run: |
          sudo apt update
          sudo apt install cmake gcc-14 g++-14 p7zip-full mold ninja-build libpq-dev libtbb-dev libmimalloc-dev libboost1.83-dev libgmp-dev libmpfr-dev libre2-dev qt6-base-dev libsfml-dev libflatbuffers-dev libavcodec-dev libavdevice-dev libavformat-dev libavfilter-dev libavutil-dev libpostproc-dev libswscale-dev libsdl2-dev

      - name: Configure amd64-avx2 release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -Bbuild_release_amd64_avx2 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON \
                -DBASIC_PROJECT_ENABLE_AVX2=ON

      - name: Build amd64-avx2 release
        run: |
          cmake --build build_release_amd64_avx2 --parallel

      - name: Create .tar.xz amd64-avx2 release artifact
        run: |
          tar -Jcvf release_amd64_avx2.tar.xz -C build_release_amd64_avx2 bin/

      - name: Create .7z amd64-avx2 release artifact
        run: |
          cd build_release_amd64_avx2 && 7z a ../release_amd64_avx2.7z bin/

      - name: Upload avx2 release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_amd64_avx2.tar.xz, release_amd64_avx2.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # armhf job
  release_armhf:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (for armhf)
        run: |
          sudo rm /etc/apt/sources.list.d/ubuntu.sources

          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "# other architecture" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null

          sudo dpkg --add-architecture armhf
          sudo apt update
          sudo apt install aptitude
          sudo aptitude install -y cmake p7zip-full mold ninja-build 
          sudo aptitude install -y libglib2.0-dev-bin:armhf libglib2.0-dev-bin-linux:armhf
          sudo aptitude install -y binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libpq-dev:armhf libtbb-dev:armhf libmimalloc-dev:armhf libboost1.83-dev:armhf libgmp-dev:armhf libmpfr-dev:armhf libre2-dev:armhf qt6-base-dev:armhf libsfml-dev:armhf libflatbuffers-dev:armhf libavcodec-dev:armhf libavdevice-dev:armhf libavformat-dev:armhf libavfilter-dev:armhf libavutil-dev:armhf libpostproc-dev:armhf libswscale-dev:armhf libsdl2-dev:armhf

      - name: Configure armhf release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc \
                -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ \
                -Bbuild_release_armhf \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON

      - name: Build armhf release
        run: |
          cmake --build build_release_armhf --parallel

      - name: Create .tar.xz armhf release artifact
        run: |
          tar -Jcvf release_armhf.tar.xz -C build_release_armhf bin/

      - name: Create .7z armhf release artifact
        run: |
          cd build_release_armhf && 7z a ../release_armhf.7z bin/

      - name: Upload armhf release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_armhf.tar.xz, release_armhf.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # arm64 job
  release_arm64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (for arm64)
        run: |
          sudo rm /etc/apt/sources.list.d/ubuntu.sources

          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "# other architecture" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null

          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install aptitude
          sudo aptitude install -y cmake p7zip-full mold ninja-build 
          sudo aptitude install -y libglib2.0-dev-bin:arm64 libglib2.0-dev-bin-linux:arm64
          sudo aptitude install -y gcc-14-aarch64-linux-gnu g++-14-aarch64-linux-gnu libpq-dev:arm64 libtbb-dev:arm64 libmimalloc-dev:arm64 libboost1.83-dev:arm64 libgmp-dev:arm64 libmpfr-dev:arm64 libre2-dev:arm64 qt6-base-dev:arm64 libsfml-dev:arm64 libflatbuffers-dev:arm64 libavcodec-dev:arm64 libavdevice-dev:arm64 libavformat-dev:arm64 libavfilter-dev:arm64 libavutil-dev:arm64 libpostproc-dev:arm64 libswscale-dev:arm64 libsdl2-dev:arm64

      - name: Configure arm64 release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++-14 \
                -Bbuild_release_arm64 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON

      - name: Build arm64 release
        run: |
          cmake --build build_release_arm64 --parallel

      - name: Create .tar.xz arm64 release artifact
        run: |
          tar -Jcvf release_arm64.tar.xz -C build_release_arm64 bin/

      - name: Create .7z arm64 release artifact
        run: |
          cd build_release_arm64 && 7z a ../release_arm64.7z bin/

      - name: Upload arm64 release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_arm64.tar.xz, release_arm64.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # riscv64 job
  release_riscv64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (for riscv64)
        run: |
          sudo rm /etc/apt/sources.list.d/ubuntu.sources

          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "# other architecture" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null
          echo "deb [arch=armhf,arm64,ppc64el,s390x,riscv64] http://ports.ubuntu.com/ubuntu-ports/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu.list > /dev/null

          sudo dpkg --add-architecture riscv64
          sudo apt update
          sudo apt install aptitude
          sudo aptitude install -y cmake p7zip-full mold ninja-build 
          sudo aptitude install -y libglib2.0-dev-bin:riscv64 libglib2.0-dev-bin-linux:riscv64
          sudo aptitude install -y gcc-14-riscv64-linux-gnu g++-14-riscv64-linux-gnu libpq-dev:riscv64 libtbb-dev:riscv64 libmimalloc-dev:riscv64 libboost1.83-dev:riscv64 libgmp-dev:riscv64 libmpfr-dev:riscv64 libre2-dev:riscv64 qt6-base-dev:riscv64 libsfml-dev:riscv64 libflatbuffers-dev:riscv64 libavcodec-dev:riscv64 libavdevice-dev:riscv64 libavformat-dev:riscv64 libavfilter-dev:riscv64 libavutil-dev:riscv64 libpostproc-dev:riscv64 libswscale-dev:riscv64 libsdl2-dev:riscv64

      - name: Configure riscv64 release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/riscv64-linux-gnu-gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/riscv64-linux-gnu-g++-14 \
                -Bbuild_release_riscv64 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON

      - name: Build riscv64 release
        run: |
          cmake --build build_release_riscv64 --parallel

      - name: Create .tar.xz riscv64 release artifact
        run: |
          tar -Jcvf release_riscv64.tar.xz -C build_release_riscv64 bin/

      - name: Create .7z riscv64 release artifact
        run: |
          cd build_release_riscv64 && 7z a ../release_riscv64.7z bin/

      - name: Upload riscv64 release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_riscv64.tar.xz, release_riscv64.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
