name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Install dependencies (for release build)
        run: |
          sudo apt update
          sudo apt install g++-14 p7zip-full mold ninja-build libtbb-dev libmimalloc-dev libboost1.83-dev libgmp-dev libmpfr-dev libre2-dev qt6-base-dev libsfml-dev libflatbuffers-dev libavcodec-dev libavdevice-dev libavformat-dev libavfilter-dev libavutil-dev libpostproc-dev libswscale-dev libsdl2-dev

      - name: Configure release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_CXX_STANDARD=20 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -Bbuild_release \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON \
                $GITHUB_WORKSPACE

      - name: Configure avx2 release build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_CXX_STANDARD=20 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -Bbuild_release_avx2 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON \
                -DBASIC_PROJECT_ENABLE_AVX2=ON \
                $GITHUB_WORKSPACE

      - name: Build release
        run: |
          cmake --build build_release --parallel

      - name: Create .tar.xz release artifact
        run: |
          tar -Jcvf release.tar.xz -C build_release bin

      - name: Create .7z release artifact
        working-directory: ${{runner.workspace}}/build_release
        run: |
          7z a release.7z -r bin

      # avx2
      - name: Build avx2 release
        run: |
          cmake --build build_release_avx2 --parallel

      - name: Create .tar.xz avx2 release artifact
        run: |
          tar -Jcvf release_avx2.tar.xz -C build_release_avx2 bin

      - name: Create .7z avx2 release artifact
        working-directory: ${{runner.workspace}}/build_release_avx2
        run: |
          7z a release_avx2.7z -r bin

      - name: Upload release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.xz, release.7z, release_avx2.tar.xz, release_avx2.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
