name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Install dependencies (for release build)
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y gcc-14 g++-14 p7zip-full mold ninja-build libtbb-dev libmimalloc-dev libboost1.83-dev libgmp-dev libmpfr-dev libre2-dev qt6-base-dev libsfml-dev libflatbuffers-dev libavcodec-dev libavdevice-dev libavformat-dev libavfilter-dev libavutil-dev libpostproc-dev libswscale-dev libsdl2-dev libpq-dev

      # Configure release build (amd64)
      - name: Configure release build
        run: |
          cmake -S . \
                -B build_release_amd64 \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON

      - name: Build amd64 release
        run: |
          cmake --build build_release_amd64 --parallel

      - name: Create .tar.xz amd64 release artifact
        run: |
          tar -Jcvf release_amd64.tar.xz -C build_release_amd64 bin/

      - name: Create .7z amd64 release artifact
        run: |
          cd build_release_amd64 && 7z a ../release.7z bin/

      - name: Configure avx2 release build
        run: |
          cmake -S . \
                -B build_release_avx2 \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/gcc-14 \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
                -GNinja \
                -DBASIC_PROJECT_STATIC_LIBSTDCXX=ON \
                -DBASIC_PROJECT_ENABLE_MOLD=ON \
                -DBASIC_PROJECT_ENABLE_GUI=ON \
                -DBASIC_PROJECT_ENABLE_AVX2=ON

      - name: Build avx2 release
        run: |
          cmake --build build_release_avx2 --parallel

      - name: Create .tar.xz avx2 release artifact
        run: |
          tar -Jcvf release_avx2.tar.xz -C build_release_avx2 bin/

      - name: Upload release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.xz, release.7z, release_avx2.tar.xz, release_avx2.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
